"""Initial schema

Revision ID: c4865f050924
Revises: 
Create Date: 2026-07-18 01:10:54.386316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4865f050924'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fusion_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('parameter_name', sa.String(length=64), nullable=False),
    sa.Column('fused_value', sa.Numeric(), nullable=True),
    sa.Column('weights_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fusion_snapshots_param_ts', 'fusion_snapshots', ['parameter_name', 'timestamp'], unique=False)
    op.create_index('idx_fusion_snapshots_ts', 'fusion_snapshots', ['timestamp'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=128), nullable=False),
    sa.Column('model_family', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('training_data_desc', sa.Text(), nullable=True),
    sa.Column('training_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('training_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('model_name', 'version')
    )
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('trigger_type', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('input_data_hash', sa.String(length=128), nullable=True),
    sa.Column('config_version', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('satellites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('agency', sa.String(length=64), nullable=True),
    sa.Column('orbit_type', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('detection_source', sa.String(length=32), nullable=False),
    sa.Column('external_catalog_id', sa.String(length=128), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('peak_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detection_confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_start_time', 'events', ['start_time'], unique=False)
    op.create_index('idx_events_status', 'events', ['status'], unique=False)
    op.create_index('idx_events_type_time', 'events', ['event_type', 'start_time'], unique=False)
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('satellite_id', 'name')
    )
    op.create_table('predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('model_run_id', sa.Integer(), nullable=True),
    sa.Column('pipeline_run_id', sa.Uuid(), nullable=True),
    sa.Column('prediction_type', sa.String(length=64), nullable=False),
    sa.Column('predicted_value', sa.Numeric(), nullable=False),
    sa.Column('predicted_unit', sa.String(length=64), nullable=False),
    sa.Column('prediction_timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('horizon_seconds', sa.Integer(), nullable=True),
    sa.Column('is_consensus', sa.Boolean(), nullable=False),
    sa.Column('base_models_included', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_predictions_consensus', 'predictions', ['event_id'], unique=False, postgresql_where=sa.text('is_consensus IS 1'))
    op.create_index('idx_predictions_event_ts', 'predictions', ['event_id', 'prediction_timestamp'], unique=False)
    op.create_table('time_series_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('parameter_name', sa.String(length=64), nullable=False),
    sa.Column('storage_type', sa.String(length=32), nullable=False),
    sa.Column('storage_location', sa.Text(), nullable=False),
    sa.Column('time_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_sec', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_observations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('satellite_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('time_series_meta_id', sa.Integer(), nullable=True),
    sa.Column('observed_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quality_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.ForeignKeyConstraint(['satellite_id'], ['satellites.id'], ),
    sa.ForeignKeyConstraint(['time_series_meta_id'], ['time_series_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('explanations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('explanation_type', sa.String(length=64), nullable=False),
    sa.Column('importance_json', sa.JSON(), nullable=True),
    sa.Column('physics_explanation', sa.Text(), nullable=True),
    sa.Column('nl_explanation', sa.Text(), nullable=True),
    sa.Column('visualization_ref', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('physics_validation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('validation_status', sa.String(length=16), nullable=False),
    sa.Column('violated_rules', sa.JSON(), nullable=True),
    sa.Column('confidence_multiplier', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('automation_allowed', sa.Boolean(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.CheckConstraint("validation_status IN ('PASS', 'SOFT_FAIL', 'HARD_FAIL')", name='ck_physics_validation_status'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('target_system', sa.String(length=64), nullable=False),
    sa.Column('recommended_action', sa.String(length=128), nullable=False),
    sa.Column('action_priority', sa.String(length=16), nullable=False),
    sa.Column('justification_text', sa.Text(), nullable=True),
    sa.Column('valid_from', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("action_priority IN ('low', 'medium', 'high', 'critical')", name='ck_recommendation_priority'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_recommendations_active', 'recommendations', ['valid_from', 'valid_until'], unique=False)
    op.create_index('idx_recommendations_stakeholder', 'recommendations', ['target_system'], unique=False)
    op.create_table('uncertainty_estimates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('lower_bound', sa.Numeric(), nullable=True),
    sa.Column('upper_bound', sa.Numeric(), nullable=True),
    sa.Column('bound_unit', sa.String(length=64), nullable=True),
    sa.Column('confidence_level', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('reliability_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('model_agreement_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('uncertainty_shape', sa.String(length=32), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('prediction_id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('prediction_id', sa.Integer(), nullable=True),
    sa.Column('recommendation_id', sa.Integer(), nullable=True),
    sa.Column('action_type', sa.String(length=64), nullable=False),
    sa.Column('action_details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recommendation_id'], ['recommendations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_event', 'audit_logs', ['event_id'], unique=False)
    op.create_index('idx_audit_logs_timestamp', 'audit_logs', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_audit_logs_timestamp', table_name='audit_logs')
    op.drop_index('idx_audit_logs_event', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('uncertainty_estimates')
    op.drop_index('idx_recommendations_stakeholder', table_name='recommendations')
    op.drop_index('idx_recommendations_active', table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('physics_validation_results')
    op.drop_table('explanations')
    op.drop_table('event_observations')
    op.drop_table('time_series_meta')
    op.drop_index('idx_predictions_event_ts', table_name='predictions')
    op.drop_index('idx_predictions_consensus', table_name='predictions', postgresql_where=sa.text('is_consensus IS 1'))
    op.drop_table('predictions')
    op.drop_table('instruments')
    op.drop_index('idx_events_type_time', table_name='events')
    op.drop_index('idx_events_status', table_name='events')
    op.drop_index('idx_events_start_time', table_name='events')
    op.drop_table('events')
    op.drop_table('users')
    op.drop_table('satellites')
    op.drop_table('pipeline_runs')
    op.drop_table('model_runs')
    op.drop_index('idx_fusion_snapshots_ts', table_name='fusion_snapshots')
    op.drop_index('idx_fusion_snapshots_param_ts', table_name='fusion_snapshots')
    op.drop_table('fusion_snapshots')
    # ### end Alembic commands ###
